# Copyright (C) 2012-2023 Zammad Foundation, https://zammad-foundation.org/

Ticket::Article::Type.find_or_create_by!(name: __('email'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('sms'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('chat'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('fax'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('phone'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('twitter status'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('twitter direct-message'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('facebook feed post'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('facebook feed comment'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('note'), communication: false)
Ticket::Article::Type.find_or_create_by!(name: __('web'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('telegram personal-message'), communication: true)
Ticket::Article::Type.find_or_create_by!(name: __('facebook direct-message'), communication: true)
