# Copyright (C) 2012-2023 Zammad Foundation, https://zammad-foundation.org/

Ticket::Article::Type.create_if_not_exists(name: __('email'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('sms'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('chat'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('fax'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('phone'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('twitter status'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('twitter direct-message'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('facebook feed post'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('facebook feed comment'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('note'), communication: false)
Ticket::Article::Type.create_if_not_exists(name: __('web'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('telegram personal-message'), communication: true)
Ticket::Article::Type.create_if_not_exists(name: __('facebook direct-message'), communication: true)
